name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: a2_test
      id: a2_test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: a2_test
        setup-command: pip install -r requirements.txt
        command: pytest tests/week01 -q
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        A2_TEST_RESULTS: "${{steps.a2_test.outputs.result}}"
      with:
        runners: a2_test
